### PR TITLE
[Enh] configuration management

### PR DESCRIPTION
**Pull request by othalla**
- default ```custom.conf``` can be source without having to cd in project dir
- accept config path/name from environment var ```CONFIG_FILE```
- update doc
- refacto config in functions
- add unit  tests for config

### CODE REVIEW

**Comment by othalla** [comment]
Any update on this?

**Comment by thomas-illiet** [comment]
Hello, can you merge this PR ?

I need this :)

**Comment by othalla** [comment]
@proteusvacuum do you still maintain this repo?

**Comment by proteusvacuum** [comment]
Thanks for this, sorry for the delay in merging! This repo is still being maintained.

**Comment by othalla** [comment]
@proteusvacuum Thank you!

**Pull request merged**
